feat: add docker image signing

diff --git a/.github/workflows/docker-images.yml b/.github/workflows/docker-images.yml
--- a/.github/workflows/docker-images.yml
+++ b/.github/workflows/docker-images.yml
@@ -34,9 +34,9 @@ env:
   PROJECT_PREFIX: dioptra
 
 jobs:
-  build-docker-dioptra-apps:
+  test-build-docker-dioptra-apps:
     runs-on: ubuntu-22.04
-    if: ${{ false }}  # disable for now
+
     strategy:
       matrix:
         dioptra-app:
@@ -44,9 +44,9 @@ jobs:
           - mlflow-tracking
           - restapi
           - pytorch-cpu
-          - pytorch-gpu
           - tensorflow2-cpu
-          - tensorflow2-gpu
+        #  - pytorch-gpu # CUDA installation exceeds GitHub runner disk space
+        #  - tensorflow2-gpu # CUDA installation exceeds GitHub runner disk space
 
     steps:
       - uses: actions/checkout@v4
@@ -57,7 +57,7 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: |
-            ${{ env.PROJECT_PREFIX }}/${{ matrix.dioptra-app }}
+            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_PREFIX }}/${{ matrix.dioptra-app }}
           tags: |
             type=schedule,pattern=nightly
             type=schedule,prefix=nightly-,pattern={{date 'YYYYMMDD'}}
@@ -70,13 +70,11 @@ jobs:
             type=sha,format=long,prefix=,suffix=
           labels: |
             org.opencontainers.image.title=${{ matrix.dioptra-app }}
-            org.opencontainers.image.description=Provides the ${{ matrix.dioptra-app }} service.
-            org.opencontainers.image.authors=NCCoE Artificial Intelligence Team <dioptra@nist.gov>, James Glasbrenner <jglasbrenner@mitre.org>, Harold Booth <harold.booth@nist.gov>, Keith Manville <kmanville@mitre.org>, Julian Sexton <jtsexton@mitre.org>, Michael Andy Chisholm, Henry Choy <hchoy@mitre.org>, Andrew Hand <ahand@mitre.org>, Bronwyn Hodges <bhodges@mitre.org>, Paul Scemama, Dmitry Cousin <dmitry.cousin@nist.gov>, Eric Trapnell <eric.trapnell@nist.gov>, Mark Trapnell <mark.trapnell@nist.gov>, Howard Huang <hhuang@mitre.org>, Paul Rowe <prowe@mitre.org>, Alexander Byrne <alexanderbyrne@mitre.org>, Luke Barner, Cory Miniter
+            org.opencontainers.image.description=Provides the ${{ matrix.dioptra-app }} microservice within the Dioptra architecture.
             org.opencontainers.image.vendor=National Institute of Standards and Technology
-            org.opencontainers.image.url=https://github.com/usnistgov/dioptra
-            org.opencontainers.image.source=https://github.com/usnistgov/dioptra
-            org.opencontainers.image.documentation=https://pages.nist.gov/dioptra
             org.opencontainers.image.licenses=NIST-PD OR CC-BY-4.0
+            org.opencontainers.image.documentation=https://pages.nist.gov/dioptra
+            org.opencontainers.image.authors=NCCoE Artificial Intelligence Team <dioptra@nist.gov>
 
       - name: set up docker qemu
         uses: docker/setup-qemu-action@v3
@@ -84,12 +82,19 @@ jobs:
       - name: set up docker buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+            registry: ghcr.io
+            username: ${{ github.actor }}
+            password: ${{ secrets.GITHUB_TOKEN }}
+
       - name: build and push
         uses: docker/build-push-action@v6
         with:
           context: .
           target: final
-          push: false
+          push: true
           load: true
           file: docker/Dockerfile.${{ matrix.dioptra-app }}
           tags: ${{ steps.meta.outputs.tags }}
@@ -97,17 +102,158 @@ jobs:
           no-cache: true
           pull: true
 
-      - name: create 'dev' tag
+      - name: extract first image tag
+        id: extract_tag
         run: |
-          docker tag ${{ env.PROJECT_PREFIX }}/${{ matrix.dioptra-app }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }} ${{ env.PROJECT_PREFIX }}/${{ matrix.dioptra-app }}:dev
+          IMAGE_TAG=$(echo ${{ steps.meta.outputs.tags }} | cut -d',' -f1)
+          echo "Using image tag: $IMAGE_TAG"
+          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-      - name: export dev-tagged image to tar.gz file
-        shell: bash
+      - name: install cosign
+        uses: sigstore/cosign-installer@v3.9.2
+
+      - name: generate cosign payload
         run: |
-          docker save ${{ env.PROJECT_PREFIX }}/${{ matrix.dioptra-app }}:dev | gzip > /tmp/${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}_dev.tar.gz
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+            IMAGE=ghcr.io/${{ steps.extract_tag.outputs.image_tag }} 
+            mkdir -p ${{ github.workspace }}/tmp
+            cosign generate $IMAGE > tmp/${APP_NAME}_payload.json
 
-      - name: archive the testing images
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.PROJECT_PREFIX }}-${{ matrix.dioptra-app }}-dev-image
-          path: /tmp/${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}_dev.tar.gz
+      - name: sign cosign payload with FIPS OpenSSL (via docker run)
+        run: |
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+            docker run --rm \
+                -v "${{ github.workspace }}:/work" \
+                -e APP_NAME=$APP_NAME \
+                registry.access.redhat.com/ubi8/ubi:8.6 \
+                bash -c '
+                dnf install -y openssl && dnf clean all && \
+                echo "${{ secrets.DIOPTRA_PRIVATE_KEY }}" > dioptra_fips.pem && \
+                chmod 400 dioptra_fips.pem && \
+                openssl version && \
+                openssl dgst -sha256 \
+                    -sign dioptra_fips.pem \
+                    -out /work/tmp/${APP_NAME}.sig \
+                    /work/tmp/${APP_NAME}_payload.json && \
+                shred -u dioptra_fips.pem
+            '
+
+      - name: verify cosign payload signature with FIPS OpenSSL (via docker run)
+        run: |
+            docker run --rm \
+                -v "${{ github.workspace }}:/work" \
+                -e APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }} \
+                registry.access.redhat.com/ubi8/ubi:8.6 \
+                bash -c '
+                dnf install -y openssl && \
+                echo "${{ secrets.DIOPTRA_PUBLIC_KEY }}" > tmp/${{ env.PROJECT_PREFIX }}.pub && \
+                openssl dgst -sha256 \
+                    -verify tmp/${{ env.PROJECT_PREFIX }}.pub \
+                    -signature /work/tmp/${APP_NAME}.sig \
+                    /work/tmp/${APP_NAME}_payload.json
+                '
+
+      - name: attach openssl signature using cosign
+        run: |
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+            IMAGE=ghcr.io/${{ steps.extract_tag.outputs.image_tag }} 
+            base64 < tmp/${APP_NAME}.sig | tr -d '\n' > tmp/${APP_NAME}_b64.sig
+
+            cosign attach signature \
+              --payload tmp/${APP_NAME}_payload.json \
+              --signature tmp/${APP_NAME}_b64.sig \
+              $IMAGE
+
+      - name: build JSON rekor entry
+        id: rekor_build_json
+        run: |
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+            HASH=$(sha256sum tmp/${APP_NAME}_payload.json | cut -d ' ' -f1
+            echo "${{ secrets.DIOPTRA_PUBLIC_KEY }}" > tmp/${{ env.PROJECT_PREFIX }}.pub )
+
+            # Signature and pub key must be base64
+            SIG_CONTENT_B64=$(base64 < tmp/${APP_NAME}.sig | tr -d '\n')
+            PUB_KEY_B64=$(base64 < tmp/${{ env.PROJECT_PREFIX }}.pub | tr -d '\n')
+
+            # Write the JSON
+            cat <<EOF > tmp/rekor_payload.json
+            {
+                "apiVersion": "0.0.1",
+                "kind": "hashedrekord",
+                "spec": {
+                    "data": {
+                        "hash": {
+                            "algorithm": "sha256",
+                            "value": "$HASH"
+                        }
+                    },
+                    "signature": {
+                        "content": "$SIG_CONTENT_B64",
+                        "publicKey": {
+                            "content": "$PUB_KEY_B64"
+                        }
+                    }
+                }
+            }
+            EOF
+            echo "Rekor payload:"
+            jq . tmp/rekor_payload.json
+
+      - name: upload JSON rekor entry
+        id: rekor_upload
+        run: |
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+
+            # Get the http response code and body
+            RESPONSE_AS_FILE=$(mktemp)
+            STATUS_CODE=$(curl -s -w "%{http_code}" -o "$RESPONSE_AS_FILE" -X POST \
+               -H "Content-Type: application/json" \
+               -d @tmp/rekor_payload.json \
+               https://rekor.sigstore.dev/api/v1/log/entries)
+
+            RESPONSE_BODY=$(cat "$RESPONSE_AS_FILE")
+            echo "rekor response:"
+            echo "$RESPONSE_BODY"
+
+            if [ "$STATUS_CODE" == "409" ]; then
+                echo "Rekor entry already exists. Checking for an existing UUID."
+                UUID=$(echo "$RESPONSE_BODY" | jq -r '.message' | grep -oE '[a-f0-9]{64,}')
+            elif [ "$STATUS_CODE" == "201" ]; then
+                echo "Rekor entry created successfully."
+                UUID=$(echo "$RESPONSE_BODY" | jq -r 'keys[0]')
+            else
+                echo "Unexpected HTTP status code: $STATUS_CODE"
+                exit 1
+            fi
+
+            if [[ ! "$UUID" =~ ^[a-f0-9]{64,}$ ]]; then
+                echo "Invalid UUID found: $UUID"
+                exit 1
+            fi
+
+            echo "rekor UUID"
+            echo "$UUID"
+            echo "UUID=$UUID" >> $GITHUB_OUTPUT
+
+      - name: install rekor-cli
+        run: |
+            curl -LO https://github.com/sigstore/rekor/releases/download/v1.3.10/rekor-cli-linux-amd64
+            chmod +x rekor-cli-linux-amd64
+            mv rekor-cli-linux-amd64 /usr/local/bin/rekor-cli
+
+      - name: verify Rekor entry
+        run: |
+            UUID="${{ steps.rekor_upload.outputs.UUID }}"
+            echo "Checking Rekor for UUID=$UUID"
+            rekor-cli get --uuid  "$UUID" \
+                --rekor_server https://rekor.sigstore.dev
+
+      - name: cosign verify
+        run: |
+            APP_NAME=${{ env.PROJECT_PREFIX }}_${{ matrix.dioptra-app }}
+            IMAGE=ghcr.io/${{ steps.extract_tag.outputs.image_tag }}
+            echo "${{ secrets.DIOPTRA_PUBLIC_KEY }}" > tmp/${{ env.PROJECT_PREFIX }}.pub 
+
+            cosign verify \
+              --key tmp/${{ env.PROJECT_PREFIX }}.pub \
+              $IMAGE
